# 全局配置
common:
  # 设置代理地址, 默认使用系统代理
  # 格式: [协议]://[主机]:[端口]
  # 如 http://127.0.0.1:7890
  proxy: ""

# 哔咔配置
bika:
  username: ""  # 用户名
  password: ""  # 密码
  # 以下为保存的cookie数据，无需修改
  nonce: ""
  token: ""

# 禁漫配置
jmcomic:
  login:
    username: ""  # 用户名
    password: ""  # 密码
    # 以下为保存的cookie数据，无需修改
    cookie: ""

# bilibili配置
bilibili:
  # B站cookie需要自己配置
  cookie: ""

twitter:
  # 部分推特视频有限制需要提供cookie，使用浏览器插件 Get cookies.txt LOCALLY 获取cookie文件并在下方设置路径
  cookie_file: ""

# 下载配置
download:
  # true: 会在下载目录下生成source.txt文件保存下载资源的来源信息，false: 不生成source.txt
  save_source_info: false

  # 漫画下载配置
  comic:
    # true: 保留下载的原始图片，false: 不保留图片
    leave_images: false
    # 漫画文件保存格式
    format:
    - cbz
    #- epub

  # 视频下载配置
  video:
    # 视频元数据文件格式
    metadata_file:
    - nfo    # 常用格式，支持emby识别
    #- vsmeta    # 支持群晖VideoStation识别
